// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB44Pc2dlIy0JjLOd6_JoeNIp-decmcWLg',
    appId: '1:524430134987:web:2fd79f69566cc4333b954e',
    messagingSenderId: '524430134987',
    projectId: 'flutter-messenger-88d41',
    authDomain: 'flutter-messenger-88d41.firebaseapp.com',
    storageBucket: 'flutter-messenger-88d41.appspot.com',
    measurementId: 'G-2TK3C62LZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqrBPFtXXoH_nhW8gArOjSt5T4HYwpPy4',
    appId: '1:524430134987:android:87429dbe6f424b783b954e',
    messagingSenderId: '524430134987',
    projectId: 'flutter-messenger-88d41',
    storageBucket: 'flutter-messenger-88d41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCarXqjoDtAcrSeBGSVbwprXquM6A5QZNc',
    appId: '1:524430134987:ios:5ef5745b58cb29cb3b954e',
    messagingSenderId: '524430134987',
    projectId: 'flutter-messenger-88d41',
    storageBucket: 'flutter-messenger-88d41.appspot.com',
    iosBundleId: 'com.example.flutterMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCarXqjoDtAcrSeBGSVbwprXquM6A5QZNc',
    appId: '1:524430134987:ios:53df54b1733376cb3b954e',
    messagingSenderId: '524430134987',
    projectId: 'flutter-messenger-88d41',
    storageBucket: 'flutter-messenger-88d41.appspot.com',
    iosBundleId: 'com.example.flutterMessenger.RunnerTests',
  );
}
